import fs from 'node:fs';
import crypto from 'node:crypto';
import { tokens, shingles, pageType, jaccard, sha256 } from './d35_similarity_v0_2.mjs';

const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const pairId=(candidateId,a,b)=>'D35PAIR-'+crypto.createHash('sha256').update([candidateId,...[a,b].sort()].join('|')).digest('hex').slice(0,12);

export function buildGold(a,b,adj){
 const bm=new Map(b.items.map(x=>[x.pair_id,x])); const dm=new Map(adj.decisions.map(x=>[x.pair_id,x]));
 const items=a.items.map(x=>{const y=bm.get(x.pair_id); const same=x.review.label===y.review.label&&x.review.page_type_valid===y.review.page_type_valid; const d=same?null:dm.get(x.pair_id); if(!same&&!d)throw new Error('missing adjudication '+x.pair_id); return {pair_id:x.pair_id,partition:x.partition,page_type:x.page_type,page_a:{url:x.page_a.url,text_sha256:x.page_a.text_sha256},page_b:{url:x.page_b.url,text_sha256:x.page_b.text_sha256},page_type_valid:same?x.review.page_type_valid:d.page_type_valid,label:same?x.review.label:d.label,resolution:same?'reviewer_consensus':'third_party_adjudication'};});
 return {gold_version:'d35-gold-v0.3',status:'laboratory_gold_not_scoring',provenance:{reviewer_a_sha256:sha256(JSON.stringify(a,null,2)),reviewer_b_sha256:sha256(JSON.stringify(b,null,2)),adjudication_sha256:sha256(JSON.stringify(adj,null,2))},counts:{total:items.length,eligible:items.filter(x=>x.page_type_valid==='yes'&&x.label!=='uncertain').length,development_eligible:items.filter(x=>x.partition==='development'&&x.page_type_valid==='yes'&&x.label!=='uncertain').length,holdout_eligible:items.filter(x=>x.partition==='holdout'&&x.page_type_valid==='yes'&&x.label!=='uncertain').length},items,scoring_authorized:false};
}

function scored(gold,snapshot){
 const pages=snapshot.pages.map(p=>({...p,kind:pageType(p),words:tokens(p.visible_text_excerpt).length,raw:shingles(p.visible_text_excerpt)})).filter(p=>p.words>=150); const clean=new Map();
 for(const cid of snapshot.candidate_ids){const own=pages.filter(p=>p.candidate_id===cid),counts=new Map(); for(const p of own)for(const sh of p.raw)counts.set(sh,(counts.get(sh)||0)+1); const min=Math.max(3,Math.ceil(own.length*.8)); const bp=own.length<3?new Set():new Set([...counts].filter(([,n])=>n>=min).map(([s])=>s)); for(const p of own)clean.set(p.page_url,new Set([...p.raw].filter(s=>!bp.has(s))));}
 return gold.items.map(x=>({...x,clean_jaccard:jaccard(clean.get(x.page_a.url)||new Set(),clean.get(x.page_b.url)||new Set())}));
}
const metrics=(rows,t)=>{let tp=0,tn=0,fp=0,fn=0; for(const r of rows){const pred=r.clean_jaccard>=t?'repeated_template':'distinct_content'; if(r.label==='repeated_template'&&pred===r.label)tp++; else if(r.label==='distinct_content'&&pred===r.label)tn++; else if(r.label==='distinct_content')fp++; else fn++;} const tpr=tp/(tp+fn||1),tnr=tn/(tn+fp||1); return {threshold:t,tp,tn,fp,fn,balanced_accuracy:(tpr+tnr)/2,accuracy:(tp+tn)/rows.length};};
export function calibrate(gold,snapshot){const rows=scored(gold,snapshot).filter(x=>x.partition==='development'&&x.page_type_valid==='yes'&&x.label!=='uncertain'); const vals=[...new Set(rows.map(x=>x.clean_jaccard))].sort((a,b)=>a-b); const candidates=[0,...vals.slice(0,-1).map((v,i)=>(v+vals[i+1])/2),1]; const trials=candidates.map(t=>metrics(rows,t)).sort((a,b)=>b.balanced_accuracy-a.balanced_accuracy||b.accuracy-a.accuracy||b.threshold-a.threshold); return {rule_version:'d35-rule-v0.3',status:'frozen_before_holdout',feature:'clean_jaccard_v0.2',prediction_rule:'repeated_template when clean_jaccard >= threshold',threshold:trials[0].threshold,development_metrics:trials[0],development_n:rows.length,gold_sha256:sha256(JSON.stringify(gold,null,2)),scoring_authorized:false};}
export function evaluate(gold,snapshot,rule){const rows=scored(gold,snapshot).filter(x=>x.partition==='holdout'&&x.page_type_valid==='yes'&&x.label!=='uncertain'); return {evaluation_version:'d35-holdout-v0.3',status:'single_holdout_evaluation',rule_sha256:sha256(JSON.stringify(rule,null,2)),gold_sha256:sha256(JSON.stringify(gold,null,2)),holdout_n:rows.length,metrics:metrics(rows,rule.threshold),cases:rows.map(x=>({pair_id:x.pair_id,label:x.label,clean_jaccard:x.clean_jaccard,prediction:x.clean_jaccard>=rule.threshold?'repeated_template':'distinct_content',correct:(x.clean_jaccard>=rule.threshold?'repeated_template':'distinct_content')===x.label})),limitations:['tiny non-independent site sample','literal internal repetition only','not authorship paraphrase or external originality'],scoring_authorized:false};}

const mode=process.argv[2]; if(mode==='gold')fs.writeFileSync(process.argv[6],JSON.stringify(buildGold(read(process.argv[3]),read(process.argv[4]),read(process.argv[5])),null,2)); else if(mode==='calibrate')fs.writeFileSync(process.argv[5],JSON.stringify(calibrate(read(process.argv[3]),read(process.argv[4])),null,2)); else if(mode==='evaluate')fs.writeFileSync(process.argv[6],JSON.stringify(evaluate(read(process.argv[3]),read(process.argv[4]),read(process.argv[5])),null,2)); else throw new Error('mode gold|calibrate|evaluate');
