import fs from 'node:fs';
import crypto from 'node:crypto';
export const normalize = text => text.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/https?:\/\/\S+/g, ' ').replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
export const shingles = (text, n = 5) => { const tokens = normalize(text).split(' ').filter(x => x.length > 1); const out = new Set(); for (let i = 0; i <= tokens.length - n; i++) out.add(tokens.slice(i, i + n).join(' ')); return out; };
export const jaccard = (a, b) => { if (!a.size && !b.size) return 0; let intersection = 0; for (const x of a) if (b.has(x)) intersection++; return intersection / (a.size + b.size - intersection); };
export function analyze(snapshot) {
 const allowed = new Set(snapshot.candidate_ids); const pages = snapshot.pages.filter(p => allowed.has(p.candidate_id)).map(p => ({...p,norm_words:normalize(p.visible_text_excerpt).split(' ').filter(Boolean).length,sh:shingles(p.visible_text_excerpt)})); const results=[];
 for (const candidateId of snapshot.candidate_ids) { const own=pages.filter(p=>p.candidate_id===candidateId&&p.norm_words>=150); const internal=[]; const cross=[]; for(let i=0;i<own.length;i++)for(let j=i+1;j<own.length;j++)internal.push({a:own[i].page_url,b:own[j].page_url,j:jaccard(own[i].sh,own[j].sh)}); for(const p of own)for(const q of pages.filter(x=>x.candidate_id!==candidateId&&x.norm_words>=150))cross.push({a:p.page_url,b:q.page_url,other:q.candidate_id,j:jaccard(p.sh,q.sh)}); internal.sort((a,b)=>b.j-a.j);cross.sort((a,b)=>b.j-a.j);results.push({candidate_id:candidateId,substantive_pages:own.length,total_pages:pages.filter(p=>p.candidate_id===candidateId).length,max_internal_jaccard:internal.length?internal[0].j:null,max_cross_candidate_jaccard:cross.length?cross[0].j:null,top_internal:internal.slice(0,3),top_cross:cross.slice(0,3)}); }
 return {method:'d35-similarity-lab-v0.1',status:'laboratory_candidate_not_scoring',parameters:{minimum_words:150,shingle_size:5,normalization:'NFKD lowercase alphanumeric',candidate_ids:snapshot.candidate_ids},input_snapshot_sha256:snapshot.snapshot_sha256,source_database_sha256:snapshot.source_database_sha256,results,limitations:['boilerplate not removed','page types not separated','exact 5-gram overlap misses paraphrase','cross-sample comparison is not external originality','no scores may be assigned']};
}
if (typeof process !== 'undefined' && process.argv?.[1]?.endsWith('d35_similarity_v0_1.mjs')) { const input=JSON.parse(fs.readFileSync(process.argv[2],'utf8')); const out=analyze(input); fs.writeFileSync(process.argv[3],JSON.stringify(out,null,2)); }
